---

- name: playbook #3
  hosts: node1.example.com
  become: yes
  tasks:
  - name: search & add parameters "net.ifnames=0" and "biosdevname=0"
    lineinfile:
      state: present
      dest: /etc/default/grub
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* {{ item }})\"[^\"]+)(\".*)'
      line: '\1 {{ item }}\2'
    loop:
    - net.ifnames=0
    - biosdevname=0

  - name: run command grub2-mkconfig
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
