---
- name: playbook #3
  hosts: node1.example.com
  become: yes
  tasks:
  - name: delete line "GRUB_CMDLINE_LINUX..."
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX'
      state: absent
  - name: add line with "net.ifnames=0 biosdevname=0"
    lineinfile:
      path: /etc/default/grub
      create: yes
      line: GRUB_CMDLINE_LINUX="no_timer_check console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 elevator=noop"
      insertafter: 'GRUB_TERMINAL_OUTPUT'
      state: present
  - name: run command grub2-mkconfig 
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
