---
- name: playbook #1
  hosts: all
  become: yes
  tasks:
  - name: remove Apache server
    yum:
      name: httpd
      state: removed
  - name: remove index.html
    file:
      path: /var/www/html/index.html
      state: absent
  - name: install firewalld
    yum:
      name: firewalld
      state: present
  - name: start service firewalld and ensure firewalld is running
    service:
      name: firewalld
      state: started
  - name: permit traffic on port 80/tcp
    firewalld:
      zone: public
      port: 80/tcp
      permanent: true
      state: disabled
  - name: permit traffic on port 443/tcp
    firewalld:
      zone: public
      port: 443/tcp
      permanent: true
      state: disabled
